# TODO: windows. https://docs.travis-ci.com/user/reference/windows/
# - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0" https://docs.travis-ci.com/user/languages/cpp/#clang-on-linux
language: cpp
sudo: false
dist: bionic
cache:
  apt: true
  directories:
#    - ffmpeg-$FF_VERSION
    - android-ndk-${NDK_VERSION}/platforms/android-{16,21}
    - android-ndk-${NDK_VERSION}/toolchains/llvm
    - android-ndk-${NDK_VERSION}/toolchains/aarch64-linux-android-4.9
    - android-ndk-${NDK_VERSION}/toolchains/arm-linux-androideabi-4.9
    - android-ndk-${NDK_VERSION}/toolchains/x86-4.9
# TODO: libav

git:
  submodules: true

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - TARGET=raspberry-pi
        - CC_VENDOR=apple
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - TARGET=host
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - TARGET=iOS
    - os: linux
      compiler: clang
      env:
        - TARGET=windows-desktop
        - _CC=clang-9
        # arm: undefined __stack_chk_guard
        - ARCHS="arm64-clang-cl-9 x86 x64" # clang-8/9 -Oz: arm64 .seh_ link error (https://travis-ci.org/wang-bin/avbuild/jobs/497331831)
      addons: #can be used in matrix, but required by every combination
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test # llvm6.0 dep
          packages:
            - clang-9
            - clang-tools-9
            - lld-9
            - llvm-9
            - sshpass
            - p7zip-full
            - nasm
            - yasm
    - os: linux
      compiler: clang
      env:
        - TARGET=raspberry-pi
        - _CC=clang-9
      addons: #can be used in matrix, but required by every combination
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test # llvm6.0 dep
          packages:
            - clang-9
            - clang-tools-9
            - lld-9
            - llvm-9
            - sshpass
    - os: linux
      compiler: clang
      env:
        - TARGET=sunxi
        - _CC=clang-9
      addons: #can be used in matrix, but required by every combination
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test # llvm6.0 dep
          packages:
            - clang-9
            - clang-tools-9
            - lld-9
            - llvm-9
            - sshpass
    - os: linux
      compiler: clang # host compiler is not used, just to tell build script to use which compiler to use from ndk. env: CC/CXX
      env:
        - TARGET=android
      addons: #can be used in matrix, but required by every combination
        apt:
          packages:
            - p7zip-full
            - nasm
            - yasm
            - sshpass

before_install:
  - $CC -v
install:
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        xcrun --show-sdk-version
        if [ "$TARGET" != "host" -a "$TARGET" != "iOS" ]; then EXTRA_BREW=llvm; fi
        brew install ${EXTRA_BREW} nasm yasm perl hudochenkov/sshpass/sshpass xz p7zip
      fi
  - |
      if [ "${TARGET:0:3}" == "win" ]; then
        lld -flavor gnu -v
        wget https://sourceforge.net/projects/avbuild/files/dep/msvcrt-dev.7z/download -O msvcrt-dev.7z
        wget https://sourceforge.net/projects/avbuild/files/dep/winsdk.7z/download -O winsdk.7z
        7z x msvcrt-dev.7z &>/dev/null
        export VCDIR=$PWD/msvcrt-dev
        7z x winsdk.7z &>/dev/null
        ./winsdk/lowercase.sh
        export WindowsSDKVersion=$(cat winsdk/.version)
        export WindowsSdkDir=$PWD/winsdk
        export PKG_CONFIG_PATH_MFX=$PWD/tools/ClangCL/lib/pkgconfig
      fi
  - |
      if [ -f ffmpeg-${FF_VERSION}/configure ]; then
        cd ffmpeg-${FF_VERSION}
        git reset --hard HEAD
        git fetch
        git checkout origin/master
        cd -
      else
        FF_BRANCH=${FF_VERSION}
        [ "$FF_BRANCH" == "master" ] || FF_BRANCH="release/$FF_BRANCH"
        git clone -b ${FF_BRANCH} --depth 1 --no-tags https://git.ffmpeg.org/ffmpeg.git ffmpeg-${FF_VERSION}
      fi
  - |
      if [ "${TARGET:0:7}" == "android" -a ! -f android-ndk-${NDK_VERSION}/ndk-build ]; then
        wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip 2>/dev/null
        7z x -y android-ndk-${NDK_VERSION}-linux-x86_64.zip >/dev/null
      fi
  - |
      if [ "$TRAVIS_OS_NAME" == "linux" -a "$TARGET" == "host" -o "$TARGET" == "windows-desktop" ]; then
        wget https://sourceforge.net/projects/avbuild/files/dep/dep.7z/download -O dep.7z
        7z x -y dep.7z -otools &>/dev/null
        if [ "$TARGET" == "host" ]; then
          export PKG_CONFIG_PATH_MFX=$PWD/tools/linux64-gcc/lib/pkgconfig
        fi
      fi
  - |
      if [ "$TARGET" == "raspberry-pi" -o "$TARGET" == "sunxi" ]; then
        wget https://sourceforge.net/projects/avbuild/files/$TARGET/${TARGET/r*pi/rpi}-sysroot.tar.xz/download -O sysroot.tar.xz
        tar Jxf sysroot.tar.xz
        export SYSROOT=$PWD/sysroot
      fi

script:
  - export FFSRC=$PWD/ffmpeg-${FF_VERSION}
  - export ANDROID_NDK=$PWD/android-ndk-${NDK_VERSION}
  - if [ -n "$_CC" -a "$TARGET" == "host" ]; then export USER_OPT="$USER_OPT --cc=$_CC"; fi  # host build
  - if [ -n "${CONFIG_SUFFIX}" ]; then ln -sf config{${CONFIG_SUFFIX},}.sh; fi
  - USE_TOOLCHAIN=${_CC:-$CC} ./avbuild.sh $TARGET "$ARCHS" # CC(gcc/clang) is set by travis depending on compiler

after_success:
  - TARGET_OS=${TARGET}
  - TARGET_OS=${TARGET_OS/#host/${TRAVIS_OS_NAME}}
  - TARGET_OS=${TARGET_OS/#osx/macOS}
  - SUFFIX=${TARGET_OS/%android/$TARGET_OS-$CC_VENDOR$CC}
  - SUFFIX=${SUFFIX/%linux/$SUFFIX-$CC_VENDOR$CC}
  - SUFFIX=${SUFFIX/%windows*/$SUFFIX-$CC_VENDOR$CC}
  - SUFFIX=${SUFFIX/%raspberry-pi/$SUFFIX-$CC_VENDOR$CC}
  - SUFFIX=${SUFFIX/%sunxi/$SUFFIX-$CC_VENDOR$CC}
  - SUFFIX=${SUFFIX}${LIB_OPT//*-/-}${CONFIG_SUFFIX}
  - mv sdk* ffmpeg-${FF_VERSION}-${SUFFIX}
  - tar Jcf ffmpeg-${FF_VERSION}-${SUFFIX}{.tar.xz,}
  - ls -hl ffmpeg-${FF_VERSION}-${SUFFIX}.tar.xz
  - sshpass -p $SF_PW scp -o StrictHostKeyChecking=no ffmpeg-${FF_VERSION}-${SUFFIX}.tar.xz $SF_USER,zero16832@frs.sourceforge.net:/home/frs/project/ffbuild/${TARGET_OS}

branches:
  only:
    - master
    - prelease
    - ci
    - /^travis.*$/

notifications:
  email:
    recipients:
      - wbsecg1@gmail.com
    on_success: change
    on_failure: always
